<?php
/**
 * @file
 * Provides a field formatter for Link fields to format them as Youtube video players.
 */


/**
 * Implementats hook_field_formatter_info().
 */
function youtube_link_formatter_field_formatter_info() {
  $formatters = array();

  $formatters['youtube_link_formatter_player'] = array(
    'label' => t('Youtube Player'),
    'description' => t('Embeds a Youtube player, if the URL is for a Youtube.com video page.'),
    'field types' => array('link_field'),
    'settings' => youtube_link_formatter_default_settings_player(),
  );

  return $formatters;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function youtube_link_formatter_field_formatter_settings_summary($field, $instance, $view_mode) {
  module_load_include('inc', 'youtube_link_formatter', 'youtube_link_formatter.admin');
  // Call the function which handles this formatter.
  $function = __FUNCTION__ . '_' . $instance['display'][$view_mode]['type'];
  return call_user_func($function, $field, $instance, $view_mode);
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function youtube_link_formatter_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  module_load_include('inc', 'youtube_link_formatter', 'youtube_link_formatter.admin');
  // Call the function which handles this formatter.
  $function = __FUNCTION__ . '_' . $instance['display'][$view_mode]['type'];
  return call_user_func($function, $field, $instance, $view_mode, $form, $form_state);
}

/**
 * Implements hook_field_formatter_view().
 */
function youtube_link_formatter_field_formatter_view(&$entity_type, &$entity, &$field, &$instance, &$langcode, &$items, &$display) {
  // Call the function which handles this formatter.
  $function = __FUNCTION__ . '_' . $display['type'];
  return call_user_func($function, $entity_type, $entity, $field, $instance, $langcode, $items, $display);
}

/**
 * Implements youtube_link_formatter_field_formatter_view_FORMATTER();
 *
 * Renders $items as <iframe>s for the youtube_link_formatter_player formatter.
 *
 * @return Array
 *    A render()-compatible array of #markup strings, E.g.
 *      <iframe src="http://player.youtube.com/video/14309120?title=0&amp;
 *      byline=0&amp;portrait=0&amp;color=c9ff23&amp;autoplay=1&amp;loop=1"
 *      width="400" height="225" frameborder="0"></iframe>
 */
function youtube_link_formatter_field_formatter_view_youtube_link_formatter_player($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  // Attributes for the <iframe>.
  // Makes IE's <iframe> borders play nicely.
  $attributes = array('frameborder' => 0);
  $settings = array('width', 'height');
  foreach ($settings as $name) {
    $attributes[$name] = $display['settings'][$name];
  }
  $player_id = drupal_html_id('youtube-player');
  $attributes['id'] = $player_id;
  $attributes = drupal_attributes($attributes);

  // Default Youtube Player formatter settings.
  $defaults = youtube_link_formatter_default_settings_player();

  // Options for Drupal's url() function.
  $url_options = array('query' => array(), 'external' => TRUE);

  // Build up the query string.
  foreach ($display['settings'] as $name => $value) {
    if (key_exists($name, $settings)) {
      $url_options['query'][$name] = $settings[$name];
    }
    else {
      $url_options['query'][$name] = $value;
    }
  }

  $ret = array();
  foreach ($items as $delta => $item) {
    // Extract the ID from the URL.
    if ($youtube = youtube_link_formatter_id($item['url'])) {
      $url = url($youtube['protocol'] . '://www.youtube.com/embed/' . $youtube['id'], $url_options);
      $title = check_plain($item['title']);
      $ret[] = array('#markup' => "<iframe title=\"$title\" src=\"$url\"$attributes></iframe>");
    }
    else {
      // The link is not a valid Youtube.com link.
      // @todo Handle this better, perhaps with node-form validation or more
      // formatter settings?
    }
  }
  return $ret;
}

/**
 * Youtube.com's default player settings.
 *
 * @see youtube_link_formatter_field_formatter_settings_form_youtube_link_formatter_player()
 *
 * @return Array
 *    Default values keyed by the setting name.
 */
function youtube_link_formatter_default_settings_player() {
  $defaults = array(
    // Use the data types that Form API forms return them as;  Integer for
    // Booleans, and Strings for text-input numbers.
    'color' => '00adef',
    'autohide' => 0,
    'autoplay' => 0,
    'loop' => 0,
    'width' => '400',
    'height' => '225',
    'enablejsapi' => 0,
    'showinfo' => 0,
    'rel' => 0,
  );
  return $defaults;
}

/**
 * Gets the Youtube ID from a youtube.com URL.
 *
 * @param $url String
 *
 * @return String
 *   The numeric ID as a string.
 */
function youtube_link_formatter_id($url) {
  preg_match('@(http|https)://(www\.)?youtube\.com/watch\?v=([A-Za-z0-9]+)@', $url, $matches);
  return isset($matches[3]) ? array ('protocol' => $matches[1], 'id' => $matches[3]) : NULL;
}
